x-app-service-base: &app-service-base
  build: ./docker/php
  image: teamdev-2026-app:latest
  environment:
    TZ: UTC
  volumes:
    - ./teamdev-2026-api/web:/work/web
    - ./scripts:/usr/local/bin/scripts
  networks:
    - teamdev-2026-shared

services:
  front:
    build: 
      context: ./
      dockerfile: ./docker/front/Dockerfile
    image: teamdev-2026-front:latest
    tty: true
    volumes:
      - ./teamdev-2026-front:/app
      - ./teamdev-2026-api/docs/openapi:/app/openapi
    working_dir: /app
    
  app:
    <<: *app-service-base
    command: ["/bin/sh", "-c", "chmod -R +x /usr/local/bin/scripts && exec php-fpm"]

  queue-worker:
    <<: *app-service-base
    working_dir: /work/web
    command: ["/bin/sh", "-c", "chmod -R +x /usr/local/bin/scripts && exec php artisan queue:work --queue=default,emails --sleep=3 --tries=3"]
    depends_on:
      - app
    restart: on-failure

  web:
    image: nginx
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./teamdev-2026-api/web:/work/web
    depends_on:
      - app
    networks:
      - teamdev-2026-shared

  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./teamdev-2026-api/docs/openapi/openapi.json:/app/openapi.json
    environment:
      SWAGGER_JSON: /app/openapi.json
    ports:
      - ${SWAGGER_PORT:-8080}:8080

networks:
  teamdev-2026-shared:
    external: true
