@startuml
left to right direction

actor "マネージャー" as Manager

rectangle "Team Domain" {

  usecase "チーム作成"
  usecase "チーム概要更新"
  usecase "チーム削除"

  usecase "チームにメンバーを追加"
  usecase "チームメンバーを削除"
  usecase "メンバー状態更新"

  usecase "チーム内ロール付与"
  usecase "チーム内ロール変更"

}

Manager --> "チーム作成"
Manager --> "チーム概要更新"
Manager --> "チーム削除"
Manager --> "チームにメンバーを追加"
Manager --> "チームメンバーを削除"
Manager --> "メンバー状態更新"
Manager --> "チーム内ロール付与"
Manager --> "チーム内ロール変更"

@enduml