#!/bin/bash
# detect-worktree.sh - Load or detect worktree and export Docker Compose isolation vars

set -e

# Check if .worktree.env exists (generated by worktree creation script)
if [ -f ".worktree.env" ]; then
  # Load pre-generated worktree environment (explicit and platform-independent)
  set -a
  source ".worktree.env"
  set +a
else
  # Fallback: Dynamic detection for main worktree or manually created setups
  # Detect worktree type
  GIT_TOPLEVEL=$(git rev-parse --show-toplevel 2>/dev/null || echo "")

  if [ -z "$GIT_TOPLEVEL" ]; then
    # Not in a git repo
    export IS_MAIN_WORKTREE="true"
    export WORKTREE_NAME="unknown"
  else
    MAIN_WORKTREE=$(git worktree list --porcelain 2>/dev/null | awk '/^worktree / {print $2; exit}' || echo "")
    export WORKTREE_NAME=$(basename "$GIT_TOPLEVEL")

    if [ -z "$MAIN_WORKTREE" ] || [ "$GIT_TOPLEVEL" = "$MAIN_WORKTREE" ]; then
      export IS_MAIN_WORKTREE="true"
    else
      export IS_MAIN_WORKTREE="false"
    fi
  fi

  # Docker Compose project namespace: canonical name for main worktree, normalized name for linked worktrees.
  if [ "$IS_MAIN_WORKTREE" = "true" ]; then
    PROJECT_NAME="teamdev-2026"
  else
    PROJECT_NAME="teamdev-2026-${WORKTREE_NAME}"
    PROJECT_NAME=$(echo "$PROJECT_NAME" | tr '/' '-' | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
  fi
  export COMPOSE_PROJECT_NAME="$PROJECT_NAME"

  # Main worktree keeps canonical web/swagger ports. Linked worktrees get deterministic offsets.
  # All worktrees share one PostgreSQL database on 5432.
  if [ "$IS_MAIN_WORKTREE" = "true" ]; then
    export WEB_PORT="80"
    export DB_PORT="5432"
    export SWAGGER_PORT="8080"
  else
    # Use od+tr to compute hash without cksum dependency (platform-independent)
    HASH=0
    for i in $(echo "$WORKTREE_NAME" | od -An -tu1 | tr -d ' '); do
      HASH=$((HASH + i))
    done
    OFFSET=$((HASH % 2000 + 1))
    export WEB_PORT="$((10080 + OFFSET))"
    export DB_PORT="5432"
    export SWAGGER_PORT="$((18080 + OFFSET))"
  fi
fi

# Optional: Print info (enable with MISE_WORKTREE_VERBOSE=1)
if [ "${MISE_WORKTREE_VERBOSE:-0}" = "1" ]; then
  if [ "$IS_MAIN_WORKTREE" = "true" ]; then
    echo "🏠 Main worktree: $WORKTREE_NAME"
  else
    echo "🌿 Linked worktree: $WORKTREE_NAME"
  fi
  echo "🐳 COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME"
  echo "🔌 WEB_PORT=$WEB_PORT DB_PORT=$DB_PORT SWAGGER_PORT=$SWAGGER_PORT"
fi
